# Generated by Django 4.1.2 on 2022-10-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='noOfGames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('UPCOMING', 'Upcoming')], max_length=100)),
                ('isDrawn', models.BooleanField()),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.team')),
            ],
        ),
    ]
