# Generated by Django 4.1.2 on 2022-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_game_isdrawn_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
