# Generated by Django 4.1.2 on 2022-11-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_stat_times_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='last_login',
        ),
    ]
